"""cart

Revision ID: ad81ccbcb5cd
Revises: 6ad1cc794850
Create Date: 2023-03-17 16:42:21.275213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad81ccbcb5cd'
down_revision = '6ad1cc794850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('productquantity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_item', 'product_quantity', ['productquantity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_column('cart_item', 'productquantity_id')
    # ### end Alembic commands ###
